class PointSetNotFound(Exception): ...
class PointSetManagerUnavailable(Exception): ...

def get_pointset_bytes(pointset_id: str) -> bytes:
    raise PointSetManagerUnavailable("PSM indisponible (stub).")
